emergencies = input("How many people need immediate first aid? ")
supplies = input("What supplies do you need? ")
transport = input("What would be the best way to transport your supplies? ")
location = input("Where should the supplies be dropped off? ")
population = input("How many people are in need? ")
